sudo: require
services:
  - docker

before_install:
  - docker build -t akif05/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run akif05/react-test npm test -- --coverage

after_success:
  - docker build -t akif05/multi-client ./client
  - docker build -t akif05/multi-nginx ./nginx
  - docker build -t akif05/multi-server ./server
  - docker build -t akif05/multi-worker ./worker

  # Log in to docker CLI
  # Add environment variables, docker id and docker pass
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those imges and push to docker hub
  - docker push akif05/multi-client
  - docker push akif05/multi-nginx
  - docker push akif05/multi-server
  - docker push akif05/multi-worker
