version: '3'
services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # Inside the container don't try to overwrite this folder
      - /app/node_modules
      # Any changes in server dir (sitting on local hd)
      # will reflect to /app dir in container
      # when container tryes to access /app directory
      # except /app/node_modules redirect to server directory
      - ./server:/app

      # Specify environment variable
      # Environment variable are in keys.js file 
      # for redis_host we can define ip address, in our 
      # case we are seting to 'redis' which is service name 
      #Dopcker will know where to connect 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client

    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
